#spring.application.name=g_52_shop2
#spring.datasource.url=jdbc:mysql://localhost:3306/g_52_shop
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.username=root
#spring.datasource.password=root
#spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
#
#key.access=KkOqMc3QoZ6ebVsnawwP0Tlysmaq6iCNlmOsgB0a/dQ=
#key.refresh=VXO0SJVx50ETJt17oqvreImZrrNzUX7ZA2APn7ny0M0=